name: Demo to create automatic PR

on:
  push:
    branches:
      - main
      - master

jobs:
  AutomaticPR:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: Raise PR 1
        id: test-1
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "PRbranchcreate1"
          base: master
          title: "demo for auto pr1"
          committer: <${{ env.GIT_COMMIT_AUTHOR_NAME }}> <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: <${{ env.GIT_COMMIT_AUTHOR_NAME }}> <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            This is to show automatic PR creation
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true

